audio:
  input_path: "/home/itinerant/medical_communication_app/data/audio_medical_com_sample.wav"
  output_path: "/home/itinerant/medical_communication_app/output/result1.json"   

pyannote:
  auth_token: "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"
  model_name: "pyannote/speaker-diarization" 

llm:
  model_name: "EleutherAI/gpt-neo-125M"